name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo build should pass
        shell: bash
        run: cargo build
      - name: opendal must be imported
        shell: bash
        run: grep "name = \"opendal\"" Cargo.lock
